sudo: required
language: bash
services:
  - docker
notifications:
  email:
    - dev@joeir.net
stages:
  - test
jobs:
  include:
  - stage: test
    script:
      - docker-compose build test
      - docker-compose run test