sudo: required
language: bash
services:
  - docker
notifications:
  email:
    - dev@joeir.net
stages:
  - test
  - name: release
    if: branch = master
jobs:
  include:
  - stage: test
    script:
      - docker-compose build tests
      - docker-compose run tests
  - stage: release
    script:
      - set -e
      - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
          git checkout ${TRAVIS_BRANCH};
          docker pull ${VERSION_TAGGER_IMAGE};
          docker run --entrypoint="iterate" -v "$(pwd):/app" ${VERSION_TAGGER_IMAGE} -q -i;
          git remote set-url origin https://${GH_USERNAME}:${GH_TOKEN}@github.com/${GH_REPO_PATH}.git;
          git push origin master --tags;
        fi;